frontend/src/Entity/Recipe.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;

/**
 * @ORM\Entity(
 *     repositoryClass = "App\Repository\RecipeRepository"
 * )
 */
class Recipe
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(
     *     type     = "integer",
     *     unique   = true)
     * @Groups("attributes")
     */
    private $id;

    /**
     * @ORM\Column(
     *     type     = "string",
     *     length   = 255)
     * @Groups("attributes")
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     * @Groups("attributes")
     */
    private $difficultyRequirement;

    /**
     * @ORM\Column(type="integer")
     * @Groups("attributes")
     */
    private $difficultyCategory_1;

    /**
     * @ORM\Column(type="integer")
     * @Groups("attributes")
     */
    private $difficultyCategory_2;

    /**
     * @ORM\Column(type="integer")
     * @Groups("attributes")
     */
    private $difficultyCategory_3;

    /**
     * @ORM\Column(type="integer")
     * @Groups("attributes")
     */
    private $difficultyCategory_4;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Groups("attributes")
     */
    private $recipeLinkUrl;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("attributes")
     */
    private $iconLinkUrl;

    /**
     * @ORM\Column(type="integer")
     * @Groups("attributes")
     */
    private $minimumAmountCreated;

    /**
     * @ORM\Column(type="integer")
     * @Groups("attributes")
     */
    private $maximumAmountCreated;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups("attributes")
     */
    private $trainingCost;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\RecipeItem")
     * @Groups("recipeRelations")
     * @MaxDepth(1)
     */
    private $recipeItem;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CraftableItem", inversedBy="recipes")
     * @Groups("recipeRelations")
     * @MaxDepth(1)
     */
    private $craftableItem;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Profession", inversedBy="recipes")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("recipeRelations")
     * @MaxDepth(1)
     */
    private $profession;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Trainer", inversedBy="recipes")
     * @Groups("recipeRelations")
     * @MaxDepth(1)
     */
    private $trainers;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Reagent", inversedBy="recipes")
     * @Groups("recipeRelations")
     * @MaxDepth(1)
     */
    private $reagents;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Character", mappedBy="recipes")
     * @Groups("recipeRelations")
     * @MaxDepth(1)
     */
    private $characters;

    public function __construct()
    {
        $this->trainers = new ArrayCollection();
        $this->reagents = new ArrayCollection();
        $this->characters = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDifficultyRequirement(): ?int
    {
        return $this->difficultyRequirement;
    }

    public function setDifficultyRequirement(int $difficultyRequirement): self
    {
        $this->difficultyRequirement = $difficultyRequirement;

        return $this;
    }

    public function getDifficultyCategory1(): ?int
    {
        return $this->difficultyCategory_1;
    }

    public function setDifficultyCategory1(int $difficultyCategory_1): self
    {
        $this->difficultyCategory_1 = $difficultyCategory_1;

        return $this;
    }

    public function getDifficultyCategory2(): ?int
    {
        return $this->difficultyCategory_2;
    }

    public function setDifficultyCategory2(int $difficultyCategory_2): self
    {
        $this->difficultyCategory_2 = $difficultyCategory_2;

        return $this;
    }

    public function getDifficultyCategory3(): ?int
    {
        return $this->difficultyCategory_3;
    }

    public function setDifficultyCategory3(int $difficultyCategory_3): self
    {
        $this->difficultyCategory_3 = $difficultyCategory_3;

        return $this;
    }

    public function getDifficultyCategory4(): ?int
    {
        return $this->difficultyCategory_4;
    }

    public function setDifficultyCategory4(int $difficultyCategory_4): self
    {
        $this->difficultyCategory_4 = $difficultyCategory_4;

        return $this;
    }

    public function getRecipeLinkUrl(): ?string
    {
        return $this->recipeLinkUrl;
    }

    public function setRecipeLinkUrl(string $recipeLinkUrl): self
    {
        $this->recipeLinkUrl = $recipeLinkUrl;

        return $this;
    }

    public function getIconLinkUrl(): ?string
    {
        return $this->iconLinkUrl;
    }

    public function setIconLinkUrl(string $iconLinkUrl): self
    {
        $this->iconLinkUrl = $iconLinkUrl;

        return $this;
    }

    public function getMinimumAmountCreated(): ?int
    {
        return $this->minimumAmountCreated;
    }

    public function setMinimumAmountCreated(int $minimumAmountCreated): self
    {
        $this->minimumAmountCreated = $minimumAmountCreated;

        return $this;
    }

    public function getMaximumAmountCreated(): ?int
    {
        return $this->maximumAmountCreated;
    }

    public function setMaximumAmountCreated(int $maximumAmountCreated): self
    {
        $this->maximumAmountCreated = $maximumAmountCreated;

        return $this;
    }

    public function getTrainingCost(): ?int
    {
        return $this->trainingCost;
    }

    public function setTrainingCost(?int $trainingCost): self
    {
        $this->trainingCost = $trainingCost;

        return $this;
    }

    public function getRecipeItem(): ?RecipeItem
    {
        return $this->recipeItem;
    }

    public function setRecipeItem(?RecipeItem $recipeItem): self
    {
        $this->recipeItem = $recipeItem;

        return $this;
    }

    public function getCraftableItem(): ?CraftableItem
    {
        return $this->craftableItem;
    }

    public function setCraftableItem(?CraftableItem $craftableItem): self
    {
        $this->craftableItem = $craftableItem;

        return $this;
    }

    public function getProfession(): ?Profession
    {
        return $this->profession;
    }

    public function setProfession(?Profession $profession): self
    {
        $this->profession = $profession;

        return $this;
    }

    /**
     * @return Collection|Trainer[]
     */
    public function getTrainers(): Collection
    {
        return $this->trainers;
    }

    public function addTrainer(Trainer $trainer): self
    {
        if (!$this->trainers->contains($trainer)) {
            $this->trainers[] = $trainer;
        }

        return $this;
    }

    public function removeTrainer(Trainer $trainer): self
    {
        if ($this->trainers->contains($trainer)) {
            $this->trainers->removeElement($trainer);
        }

        return $this;
    }

    /**
     * @return Collection|Reagent[]
     */
    public function getReagents(): Collection
    {
        return $this->reagents;
    }

    public function addReagent(Reagent $reagent): self
    {
        if (!$this->reagents->contains($reagent)) {
            $this->reagents[] = $reagent;
        }

        return $this;
    }

    public function removeReagent(Reagent $reagent): self
    {
        if ($this->reagents->contains($reagent)) {
            $this->reagents->removeElement($reagent);
        }

        return $this;
    }

    /**
     * @return Collection|Character[]
     */
    public function getCharacters(): Collection
    {
        return $this->characters;
    }

    public function addCharacter(Character $character): self
    {
        if (!$this->characters->contains($character)) {
            $this->characters[] = $character;
            $character->addRecipe($this);
        }

        return $this;
    }

    public function removeCharacter(Character $character): self
    {
        if ($this->characters->contains($character)) {
            $this->characters->removeElement($character);
            $character->removeRecipe($this);
        }

        return $this;
    }
}

frontend/templates/recipe/create.html.twig
{% extends 'entity/create.html.twig' %}

{% block form %}
    <div class="container-fluid px-5 mb-3">
        {{ form_start(form) }}

        {{ form_row(form.name) }}
        {{ form_row(form.recipeLinkUrl) }}
        {{ form_row(form.iconLinkUrl) }}
        {{ form_row(form.difficultyRequirement) }}
        {{ form_row(form.difficultyCategory1, {'label': 'Difficulty Category 1'}) }}
        {{ form_row(form.difficultyCategory2, {'label': 'Difficulty Category 2'}) }}
        {{ form_row(form.difficultyCategory3, {'label': 'Difficulty Category 3'}) }}
        {{ form_row(form.difficultyCategory4, {'label': 'Difficulty Category 4'}) }}
        {{ form_row(form.minimumAmountCreated) }}
        {{ form_row(form.maximumAmountCreated) }}

        {# Profession #}
        <div class="form-group">
            {{ form_label(form.profession) }}
            {{ form_errors(form.profession) }}
            {{ form_help(form.profession) }}
            <div>
                {{ form_widget(form.profession) }}
            </div>
        </div>

        {# Craftable item #}
        <div class="form-group">
            {{ form_label(form.craftableItem) }}
            {{ form_errors(form.craftableItem) }}
            {{ form_help(form.craftableItem) }}
            <div>
                {{ form_widget(form.craftableItem) }}
            </div>
        </div>

        {# Recipe item #}
        <div class="form-group">
            {{ form_label(form.recipeItem) }}
            {{ form_errors(form.recipeItem) }}
            {{ form_help(form.recipeItem) }}
            <div>
                {{ form_widget(form.recipeItem) }}
            </div>
        </div>

        {# Reagents #}
        <div class="form-group">
            {{ form_label(form.reagents) }}
            {{ form_errors(form.reagents) }}
            {{ form_help(form.reagents) }}
            <ol>
                {% for reagent in form.reagents %}
                    <li>
                        {{ form_widget(reagent) }}
                        {{ form_label(reagent, null, { 'label_attr': { 'class': 'form-check-label' } }) }}
                    </li>
                {% endfor %}
            </ol>
        </div>

        {# Trainers #}
        <div class="form-group">
            {{ form_label(form.trainers) }}
            {{ form_errors(form.trainers) }}
            {{ form_help(form.trainers) }}
            <ol>
                {% for trainer in form.trainers %}
                    <li>
                        {{ form_widget(trainer) }}
                        {{ form_label(trainer, null, { 'label_attr': { 'class': 'form-check-label' } }) }}
                    </li>
                {% endfor %}
            </ol>
        </div>
        {{ form_row(form.trainingCost) }}

        {# Characters #}
        <div class="form-group">
            {{ form_label(form.characters) }}
            {{ form_errors(form.characters) }}
            {{ form_help(form.characters) }}
            <ol>
                {% for character in form.characters %}
                    <li>
                        {{ form_widget(character) }}
                        {{ form_label(character, null, { 'label_attr': { 'class': 'form-check-label' } }) }}
                    </li>
                {% endfor %}
            </ol>
        </div>

        {{ form_end(form) }}
    </div>
{% endblock form %}

frontend/templates/recipe/edit.html.twig
{% extends 'entity/edit.html.twig' %}

{% block form %}
    <div class="container-fluid px-5 mb-3">
        {{ form_start(form) }}

        {{ form_row(form.name) }}
        {{ form_row(form.recipeLinkUrl) }}
        {{ form_row(form.iconLinkUrl) }}
        {{ form_row(form.difficultyRequirement) }}
        {{ form_row(form.difficultyCategory1, {'label': 'Difficulty Category 1'}) }}
        {{ form_row(form.difficultyCategory2, {'label': 'Difficulty Category 2'}) }}
        {{ form_row(form.difficultyCategory3, {'label': 'Difficulty Category 3'}) }}
        {{ form_row(form.difficultyCategory4, {'label': 'Difficulty Category 4'}) }}
        {{ form_row(form.minimumAmountCreated) }}
        {{ form_row(form.maximumAmountCreated) }}

        {# Profession #}
        <div class="form-group">
            {{ form_label(form.profession) }}
            {{ form_errors(form.profession) }}
            {{ form_help(form.profession) }}
            <div>
                {{ form_widget(form.profession) }}
            </div>
        </div>

        {# Craftable item #}
        <div class="form-group">
            {{ form_label(form.craftableItem) }}
            {{ form_errors(form.craftableItem) }}
            {{ form_help(form.craftableItem) }}
            <div>
                {{ form_widget(form.craftableItem) }}
            </div>
        </div>

        {# Recipe item #}
        <div class="form-group">
            {{ form_label(form.recipeItem) }}
            {{ form_errors(form.recipeItem) }}
            {{ form_help(form.recipeItem) }}
            <div>
                {{ form_widget(form.recipeItem) }}
            </div>
        </div>

        {# Reagents #}
        <div class="form-group">
            {{ form_label(form.reagents) }}
            {{ form_errors(form.reagents) }}
            {{ form_help(form.reagents) }}
            <ol>
                {% for reagent in form.reagents %}
                    <li>
                        {{ form_widget(reagent) }}
                        {{ form_label(reagent, null, { 'label_attr': { 'class': 'form-check-label' } }) }}
                    </li>
                {% endfor %}
            </ol>
        </div>

        {# Trainers #}
        <div class="form-group">
            {{ form_label(form.trainers) }}
            {{ form_errors(form.trainers) }}
            {{ form_help(form.trainers) }}
            <ol>
                {% for trainer in form.trainers %}
                    <li>
                        {{ form_widget(trainer) }}
                        {{ form_label(trainer, null, { 'label_attr': { 'class': 'form-check-label' } }) }}
                    </li>
                {% endfor %}
            </ol>
        </div>
        {{ form_row(form.trainingCost) }}

        {# Characters #}
        <div class="form-group">
            {{ form_label(form.characters) }}
            {{ form_errors(form.characters) }}
            {{ form_help(form.characters) }}
            <ol>
                {% for character in form.characters %}
                    <li>
                        {{ form_widget(character) }}
                        {{ form_label(character, null, { 'label_attr': { 'class': 'form-check-label' } }) }}
                    </li>
                {% endfor %}
            </ol>
        </div>

        {{ form_end(form) }}
    </div>
{% endblock form %}

frontend/templates/recipe/index.html.twig
{% extends 'entity/index.html.twig' %}

frontend/templates/recipe/show.html.twig
{% extends 'entity/show.html.twig' %}

{% block title %}{{ recipe.getName() }}{% endblock title %}

{% block information %}
    <p>Icon:
        <img src="{{ recipe.getIconLinkUrl|replace({'small': 'medium', 'large': 'medium'}) }}"
             alt="An icon representing the {{ recipe.getName() }} recipe">
    </p>
    <a href="{{ recipe.getRecipeLinkUrl() }}" target="_blank">Link to WoWHead page</a>

    {% if recipe.getMinimumAmountCreated() != recipe.getMaximumAmountCreated() %}
        <p>Amount created: {{ recipe.getMinimumAmountCreated() }} - {{ recipe.getMaximumAmountCreated }}</p>
    {% else %}
        <p>Amount created: {{ recipe.getMinimumAmountCreated() }}</p>
    {% endif %}

    <p>Difficulty requirement: {{ recipe.getDifficultyRequirement() }}</p>
    <p>Difficulty categories:
        <span class="contrast">
                                <span class="difficulty-category-1">{{ recipe.getDifficultyCategory1() }}</span>
                                <span class="difficulty-category-2">{{ recipe.getDifficultyCategory2() }}</span>
                                <span class="difficulty-category-3">{{ recipe.getDifficultyCategory3() }}</span>
                                <span class="difficulty-category-4">{{ recipe.getDifficultyCategory4() }}</span>
        </span>
    </p>

    <p>Profession: {{ recipe.getProfession().getName() }}</p>

    {% if recipe.getRecipeItem() != null %}
        <p>Recipe item:
            <a href="/recipe-items/{{ recipe.getRecipeItem().getId() }}">{{ recipe.getRecipeItem().getName() }}</a>
        </p>
    {% else %}
        <p>{{ recipe.getName() }} isn't taught by a recipe item.</p>
    {% endif %}

    {% if recipe.getCraftableItem() != null %}
        <p>
            <a href="/craftable-items/{{ recipe.getCraftableItem().getName() }}">{{ recipe.getCraftableItem().getName() }}</a>
        </p>
    {% else %}
        <p>{{ recipe.getName() }} doesn't create an item.</p>
    {% endif %}

    {% if recipe.getTrainers()|length > 0 %}
        <p>{{ recipe.getName() }} is taught by the following trainers: </p>
        <ol>
            {% for trainer in recipe.getTrainers() %}
                <li>
                    <a href="/trainers/{{ trainer.getId() }}">{{ trainer.getName() }}</a>
                </li>
            {% endfor %}
        </ol>
    {% else %}
        <p>{{ recipe.getName() }} isn't taught by trainers.</p>
    {% endif %}

    {% if recipe.getTrainingCost() != null %}
        <p>Training cost: {{ recipe.getTrainingCost() }}</p>
    {% else %}
        <p>{{ recipe.getName() }} can't be trained.</p>
    {% endif %}

    {% if recipe.getReagents()|length > 0 %}
        <p>{{ recipe.getName() }} requires the following reagents: </p>
        <ol>
            {% for reagent in recipe.getReagents() %}
                <li>
                    <a href="/reagents/{{ reagent.getId() }}">{{ reagent.getName() }}</a>
                </li>
            {% endfor %}
        </ol>
    {% else %}
        <p>{{ recipe.getName() }} requires no reagents.</p>
    {% endif %}

    {% if recipe.getCharacters()|length > 0 %}
        <p>The following characters know {{ recipe.getName() }}: </p>
        <ol>
            {% for character in recipe.getCharacters() %}
                <li>
                    <a href="/characters/{{ character.getId() }}">{{ character.getName() }}</a>
                </li>
            {% endfor %}
        </ol>
    {% else %}
        <p>No characters know {{ recipe.getName() }}.</p>
    {% endif %}
{% endblock information %}